GET http://localhost:5016/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJpY2t5LnYubG9wZXoiLCJzdWIiOiJyaWNreS52LmxvcGV6IiwianRpIjoiOWQ5NDU0ZjMiLCJyb2xlIjoidXNlciIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjM5NDI0IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTYiLCJodHRwOi8vbG9jYWxob3N0OjUwMTYiLCJodHRwczovL2xvY2FsaG9zdDo3MTgxIl0sIm5iZiI6MTcxMjAxNDY2NSwiZXhwIjoxNzE5ODc3MDY1LCJpYXQiOjE3MTIwMTQ2NjYsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.gPKgcScIIeVKW0wGRMoaTpC19vQ1oGhR08UNldgZzxI


###
GET http://localhost:5016/authors/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJpY2t5LnYubG9wZXoiLCJzdWIiOiJyaWNreS52LmxvcGV6IiwianRpIjoiOWQ5NDU0ZjMiLCJyb2xlIjoidXNlciIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjM5NDI0IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTYiLCJodHRwOi8vbG9jYWxob3N0OjUwMTYiLCJodHRwczovL2xvY2FsaG9zdDo3MTgxIl0sIm5iZiI6MTcxMjAxNDY2NSwiZXhwIjoxNzE5ODc3MDY1LCJpYXQiOjE3MTIwMTQ2NjYsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.gPKgcScIIeVKW0wGRMoaTpC19vQ1oGhR08UNldgZzxI



###
POST http://localhost:5016/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJpY2t5LnYubG9wZXoiLCJzdWIiOiJyaWNreS52LmxvcGV6IiwianRpIjoiZTA3ZjUzZmIiLCJyb2xlIjpbImFkbWluIiwidXNlciJdLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDozOTQyNCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0Mzk2IiwiaHR0cDovL2xvY2FsaG9zdDo1MDE2IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE4MSJdLCJuYmYiOjE3MTIwMTQ5NzcsImV4cCI6MTcxOTg3NzM3NywiaWF0IjoxNzEyMDE0OTc4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.n0M_uUr8gNMRqjNB64YG8Xk10qcGKTWhoh6vALy6X84
Content-Type: application/json

{ 
    "FirstName": "Maria",
    "LastName": "Garcia",
    "Gender": "Male",
    "DateOfBirth": "1995-12-15"
}

